###################################################################
###################################################################
#
#	Makefile for NWS/COMET specific Eta model related software
#		Top level
#		NWS 11/99 R.Rozumalski
#
####################################################################
####################################################################
#
#

.SILENT:

include $(ETA_HOME)/src/config/Makeinc.common

all :
	(cd $(ETA_OS); echo "    Making $@ in `pwd`" ; $(MAKE) $@; echo " ")

All : all

clean :
	(cd $(ETA_OS); echo "    Making $@ in `pwd`" ; $(MAKE) $@; echo " ")

CLEAN : clean

clobber:
	(cd $(ETA_OS); echo "    Making $@ in `pwd`" ; $(MAKE) $@; echo " ")

CLOBBER: clobber

