      SUBROUTINE ERREXIT(IRET)
C$$$  SUBPROGRAM DOCUMENTATION  BLOCK
C                .      .    .                                       .
C SUBPROGRAM:  ERREXIT       EXIT WITH A RETURN CODE
C   PRGMMR: IREDELL          ORG: NP23        DATE:1998-06-04
C
C ABSTRACT: EXIT WITH A RETURN CODE
C
C PROGRAM HISTORY LOG:
C   1998-06-04  IREDELL
C
C USAGE:    CALL ERREXIT(IRET)
C   INPUT ARGUMENT LIST:
C     IRET     - INTEGER RETURN CODE
C
C SUBPROGRAMS CALLED:
C   EXIT       - EXITS FROM A FORTRAN PROGRAM
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 90
C
C$$$
      CALL EXIT(IRET)
      END
